-- MySQL Script generated by MySQL Workbench
-- Tue Oct  2 23:39:11 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ppe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ppe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ppe` DEFAULT CHARACTER SET utf8 ;
USE `ppe` ;

-- -----------------------------------------------------
-- Table `ppe`.`salles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ppe`.`salles` (
  `num_salle` INT NOT NULL AUTO_INCREMENT,
  `nom_salle` VARCHAR(20) NOT NULL,
  `nombre_place` INT NOT NULL,
  `informatisee` TINYINT NULL,
  PRIMARY KEY (`num_salle`),
  UNIQUE INDEX `num_salle_UNIQUE` (`num_salle` ASC),
  UNIQUE INDEX `nom_salle_UNIQUE` (`nom_salle` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppe`.`ligues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ppe`.`ligues` (
  `num_ligues` INT NOT NULL AUTO_INCREMENT,
  `nom_ligue` VARCHAR(20) NOT NULL,
  `sport` VARCHAR(20) NOT NULL,
  `tel` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`num_ligues`),
  UNIQUE INDEX `num_ligues_UNIQUE` (`num_ligues` ASC),
  UNIQUE INDEX `nom_ligue_UNIQUE` (`nom_ligue` ASC),
  UNIQUE INDEX `sport_UNIQUE` (`sport` ASC),
  UNIQUE INDEX `tel_UNIQUE` (`tel` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppe`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ppe`.`roles` (
  `id_role` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_role`),
  UNIQUE INDEX `rolescol_UNIQUE` (`role` ASC),
  UNIQUE INDEX `id_roles_UNIQUE` (`id_role` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppe`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ppe`.`users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(13) NOT NULL,
  `id_role` INT NOT NULL,
  PRIMARY KEY (`id_users`, `id_role`),
  UNIQUE INDEX `id_users_UNIQUE` (`id_users` ASC),
  INDEX `fk_users_roles1_idx` (`id_role` ASC),
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`id_role`)
    REFERENCES `ppe`.`roles` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppe`.`reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ppe`.`reservations` (
  `num_reservation` INT NOT NULL AUTO_INCREMENT,
  `date_demande` DATE NOT NULL,
  `debut_reservation` DATETIME NOT NULL,
  `fin_reservation` DATETIME NOT NULL,
  `commentaire` VARCHAR(1000) NULL,
  `num_salle` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id_role` INT NOT NULL,
  PRIMARY KEY (`num_reservation`, `num_salle`, `id_user`, `id_role`),
  UNIQUE INDEX `num_reservation_UNIQUE` (`num_reservation` ASC),
  INDEX `fk_reservation_salles1_idx` (`num_salle` ASC),
  INDEX `fk_reservation_users1_idx` (`id_user` ASC, `id_role` ASC),
  CONSTRAINT `fk_reservation_salles1`
    FOREIGN KEY (`num_salle`)
    REFERENCES `ppe`.`salles` (`num_salle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_users1`
    FOREIGN KEY (`id_user` , `id_role`)
    REFERENCES `ppe`.`users` (`id_users` , `id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ppe`.`users_ligues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ppe`.`users_ligues` (
  `id_user` INT NOT NULL,
  `num_ligue` INT NOT NULL,
  `responssable` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_user`, `num_ligue`),
  INDEX `fk_users_ligues_ligues1_idx` (`num_ligue` ASC),
  INDEX `fk_users_ligues_users1_idx` (`id_user` ASC),
  CONSTRAINT `fk_users_ligues_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `ppe`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_ligues_ligues1`
    FOREIGN KEY (`num_ligue`)
    REFERENCES `ppe`.`ligues` (`num_ligues`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;